### ISSUE TITLE
[nb_conda_kernels] enabled, 0 kernels found After registering R image sample to Sagemaker Studio

### ISSUE THREAD

**Issue by mvsantos013** [aws-samples/sagemaker-studio-custom-image-samples#4]
After building, deploying to ECR, attaching to Sagemaker Studio the [R image sample](https://github.com/aws-samples/sagemaker-studio-custom-image-samples/blob/main/examples/r-image/Dockerfile) and trying to run the kernel I get Kernel Dead error with these logs:

```
2020-11-26T13:03:33.471-03:00 | + CONDA_DIR=/opt/.sagemakerinternal/conda
-- | --
  | 2020-11-26T13:03:33.471-03:00 | + CONDA_ENV_FILTER=/opt/conda$
  | 2020-11-26T13:03:33.471-03:00 | + command -v python
  | 2020-11-26T13:03:33.471-03:00 | + [ 0 -eq 0 ]
  | 2020-11-26T13:03:33.471-03:00 | + python -c from __future__ import print_function;import sys; print(sys.prefix)
  | 2020-11-26T13:03:33.471-03:00 | + SYSTEM_PYTHON_PREFIX=/opt/conda
  | 2020-11-26T13:03:33.471-03:00 | + export JUPYTER_PATH=/opt/conda/share/jupyter/
  | 2020-11-26T13:03:33.471-03:00 | + [ ! -f /opt/conda/share/jupyter/kernels/python3/kernel.json ]
  | 2020-11-26T13:03:33.471-03:00 | + [ ! -z Custom ]
  | 2020-11-26T13:03:33.471-03:00 | + [ Custom = DLC ]
  | 2020-11-26T13:03:33.471-03:00 | + [ Custom = Studio ]
  | 2020-11-26T13:03:33.471-03:00 | + echo This is not a DLC/Studio image (found Custom), so not adding Python3 kernel.
  | 2020-11-26T13:03:33.471-03:00 | + export PATH=/opt/conda/bin:/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/miniconda3/condabin:/tmp/anaconda3/condabin:/tmp/miniconda2/condabin:/tmp/anaconda2/condabin
  | 2020-11-26T13:03:33.471-03:00 | + /opt/.sagemakerinternal/conda/bin/jupyter-kernelgateway --ip 0.0.0.0 --port 8888 --JupyterWebsocketPersonality.list_kernels=True --KernelSpecManager.ensure_native_kernel=False --MultiKernelManager.default_kernel_name= --KernelGatewayApp.kernel_spec_manager_class=nb_conda_kernels.CondaKernelSpecManager --CondaKernelSpecManager.env_filter=/opt/conda$
  | 2020-11-26T13:03:33.471-03:00 | This is not a DLC/Studio image (found Custom), so not adding Python3 kernel.
  | 2020-11-26T13:03:33.471-03:00 | [KernelGatewayApp] [nb_conda_kernels] enabled, 0 kernels found
  | 2020-11-26T13:03:38.782-03:00 | [KernelGatewayApp] Jupyter Kernel Gateway at http://0.0.0.0:8888
  | 2020-11-26T13:03:48.730-03:00 | [E 201126 16:03:48 web:1792] Uncaught exception POST /api/kernels (169.255.250.1) HTTPServerRequest(protocol='http', host='10.10.21.72:32774', method='POST', uri='/api/kernels', version='HTTP/1.1', remote_ip='169.255.250.1') Traceback (most recent call last): File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute result = await result File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/kernel_gateway/services/kernels/handlers.py", line 63, in post yield super(MainKernelHandler, self).post() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 46, in post kernel_id = yield maybe_future(km.start_kernel(kernel_name=model['name'])) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/kernel_gateway/services/kernels/manager.py", line 83, in start_kernel kernel_id = yield gen.maybe_future(super(SeedingMappingKernelManager, self).start_kernel(*args, **kwargs)) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper yielded = next(result) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel super(MappingKernelManager, self).start_kernel(**kwargs) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel km.start_kernel(**kwargs) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 309, in start_kernel kernel_cmd, kw = self.pre_start_kernel(**kw) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 262, in pre_start_kernel kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 181, in format_kernel_cmd cmd = self.kernel_spec.argv + extra_arguments File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 87, in kernel_spec self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/nb_conda_kernels/manager.py", line 327, in get_kernel_spec res = super(CondaKernelSpecManager, self).get_kernel_spec(kernel_name) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 235, in get_kernel_spec raise NoSuchKernel(kernel_name) jupyter_client.kernelspec.NoSuchKernel: No such kernel named hdx-r-kernel
  | 2020-11-26T13:03:48.730-03:00 | [E 201126 16:03:48 log:48] { "Authorization": "token", "Connection": "close", "Host": "10.10.21.72:32774", "Content-Length": "117", "Content-Type": "application/x-www-form-urlencoded", "Accept-Encoding": "gzip" }
  | 2020-11-26T13:03:53.471-03:00 | [E 201126 16:03:48 log:49] 500 POST /api/kernels (169.255.250.1) 294.59ms referer=None
```
Am I doing something wrong?

**Comment by jaipreet-s** [comment]
The relevant error is in this line in the logs you've provided

```
  | 2020-11-26T13:03:48.730-03:00 | [E 201126 16:03:48 web:1792] Uncaught exception POST /api/kernels (169.255.250.1) HTTPServerRequest(protocol='http', host='10.10.21.72:32774', method='POST', uri='/api/kernels', version='HTTP/1.1', remote_ip='169.255.250.1') Traceback (most recent call last): File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute result = await result File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/kernel_gateway/services/kernels/handlers.py", line 63, in post yield super(MainKernelHandler, self).post() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 46, in post kernel_id = yield maybe_future(km.start_kernel(kernel_name=model['name'])) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/kernel_gateway/services/kernels/manager.py", line 83, in start_kernel kernel_id = yield gen.maybe_future(super(SeedingMappingKernelManager, self).start_kernel(*args, **kwargs)) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper yielded = next(result) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel super(MappingKernelManager, self).start_kernel(**kwargs) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel km.start_kernel(**kwargs) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 309, in start_kernel kernel_cmd, kw = self.pre_start_kernel(**kw) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 262, in pre_start_kernel kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 181, in format_kernel_cmd cmd = self.kernel_spec.argv + extra_arguments File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 87, in kernel_spec self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/nb_conda_kernels/manager.py", line 327, in get_kernel_spec res = super(CondaKernelSpecManager, self).get_kernel_spec(kernel_name) File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 235, in get_kernel_spec raise NoSuchKernel(kernel_name) jupyter_client.kernelspec.NoSuchKernel: No such kernel named hdx-r-kernel
```

And digging even further this is the relevant error from Jupyter *jupyter_client.kernelspec.NoSuchKernel: No such kernel named hdx-r-kernel*

It looks like you've provided `hdx-r-kernel` as the kernel name in your AppImageConfig but the actual kernel name in this image is [ir](https://github.com/aws-samples/sagemaker-studio-custom-image-samples/blob/main/examples/r-image/app-image-config-input.json). When Jupyter tries to launch a kernel with that name, it fails because the kernel does not exist in the image.

**Comment by mvsantos013** [comment]
Changing image name worked for me, thanks. I also had to change r-base version to v4.0.3
